package com.real.fudousan.entry.vo;

import java.io.Serializable;
import java.util.Date;

import com.real.fudousan.agency.vo.Agency;
import com.real.fudousan.estate.vo.Estate;

/**
 * 매물을 올린 부동산 업체 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Entry implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 부동산중개사무소. */
	private Agency agency;

	/** 매물. */
	private Estate estate;

	/** DATE. */
	private Date date;

	/** PRICE. */
	private Integer price;
}
