package com.real.fudousan.agency.vo;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.real.fudousan.entry.vo.Entry;
import com.real.fudousan.estate.vo.TransType;
import com.real.fudousan.member.vo.Member;

/**
 * 부동산중개사무소 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Agency implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** AGENCY_ID. */
	private Integer agencyId;

	/** 회원. */
	private Member member;

	/** 중개소이름. */
	private String name;

	/** 사업번호. */
	private int biznum;

	/** 주소 대분류. */
	private String addressMain;

	/** 주소 중분류. */
	private String addressMiddle;

	/** 주소 소분류. */
	private String addressSmall;

	/** 주소 상세. */
	private String addressSub;

	/** 설명. */
	private String text;

	/** 거래 유형. */
	private TransType transType;

	/** CONFIRM. */
	private Integer confirm;

	/** DATE. */
	private Date date;

	/** DEL_DATE. */
	private Date delDate;

	/** GPS_X. */
	private Integer gpsX;

	/** GPS_Y. */
	private Integer gpsY;

	/** 매물을 올린 부동산 업체 목록. */
	private Set<Entry> entrySet;

	/**
	 * 생성자.
	 */
	public Agency() {
		this.entrySet = new HashSet<Entry>();
	}

	/**
	 * AGENCY_ID을 설정합니다..
	 * 
	 * @param agencyId
	 *            AGENCY_ID
	 */
	public void setAgencyId(Integer agencyId) {
		this.agencyId = agencyId;
	}

	/**
	 * AGENCY_ID을 가져옵니다..
	 * 
	 * @return AGENCY_ID
	 */
	public Integer getAgencyId() {
		return this.agencyId;
	}

	/**
	 * 회원을 설정합니다..
	 * 
	 * @param member
	 *            회원
	 */
	public void setMember(Member member) {
		this.member = member;
	}

	/**
	 * 회원을 가져옵니다..
	 * 
	 * @return 회원
	 */
	public Member getMember() {
		return this.member;
	}

	/**
	 * 중개소이름을 설정합니다..
	 * 
	 * @param name
	 *            중개소이름
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * 중개소이름을 가져옵니다..
	 * 
	 * @return 중개소이름
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * 사업번호을 설정합니다..
	 * 
	 * @param biznum
	 *            사업번호
	 */
	public void setBiznum(int biznum) {
		this.biznum = biznum;
	}

	/**
	 * 사업번호을 가져옵니다..
	 * 
	 * @return 사업번호
	 */
	public int getBiznum() {
		return this.biznum;
	}

	/**
	 * 주소 대분류을 설정합니다..
	 * 
	 * @param addressMain
	 *            주소 대분류
	 */
	public void setAddressMain(String addressMain) {
		this.addressMain = addressMain;
	}

	/**
	 * 주소 대분류을 가져옵니다..
	 * 
	 * @return 주소 대분류
	 */
	public String getAddressMain() {
		return this.addressMain;
	}

	/**
	 * 주소 중분류을 설정합니다..
	 * 
	 * @param addressMiddle
	 *            주소 중분류
	 */
	public void setAddressMiddle(String addressMiddle) {
		this.addressMiddle = addressMiddle;
	}

	/**
	 * 주소 중분류을 가져옵니다..
	 * 
	 * @return 주소 중분류
	 */
	public String getAddressMiddle() {
		return this.addressMiddle;
	}

	/**
	 * 주소 소분류을 설정합니다..
	 * 
	 * @param addressSmall
	 *            주소 소분류
	 */
	public void setAddressSmall(String addressSmall) {
		this.addressSmall = addressSmall;
	}

	/**
	 * 주소 소분류을 가져옵니다..
	 * 
	 * @return 주소 소분류
	 */
	public String getAddressSmall() {
		return this.addressSmall;
	}

	/**
	 * 주소 상세을 설정합니다..
	 * 
	 * @param addressSub
	 *            주소 상세
	 */
	public void setAddressSub(String addressSub) {
		this.addressSub = addressSub;
	}

	/**
	 * 주소 상세을 가져옵니다..
	 * 
	 * @return 주소 상세
	 */
	public String getAddressSub() {
		return this.addressSub;
	}

	/**
	 * 설명을 설정합니다..
	 * 
	 * @param text
	 *            설명
	 */
	public void setText(String text) {
		this.text = text;
	}

	/**
	 * 설명을 가져옵니다..
	 * 
	 * @return 설명
	 */
	public String getText() {
		return this.text;
	}

	/**
	 * 거래 유형을 설정합니다..
	 * 
	 * @param transType
	 *            거래 유형
	 */
	public void setTransType(TransType transType) {
		this.transType = transType;
	}

	/**
	 * 거래 유형을 가져옵니다..
	 * 
	 * @return 거래 유형
	 */
	public TransType getTransType() {
		return this.transType;
	}

	/**
	 * CONFIRM을 설정합니다..
	 * 
	 * @param confirm
	 *            CONFIRM
	 */
	public void setConfirm(Integer confirm) {
		this.confirm = confirm;
	}

	/**
	 * CONFIRM을 가져옵니다..
	 * 
	 * @return CONFIRM
	 */
	public Integer getConfirm() {
		return this.confirm;
	}

	/**
	 * DATE을 설정합니다..
	 * 
	 * @param date
	 *            DATE
	 */
	public void setDate(Date date) {
		this.date = date;
	}

	/**
	 * DATE을 가져옵니다..
	 * 
	 * @return DATE
	 */
	public Date getDate() {
		return this.date;
	}

	/**
	 * DEL_DATE을 설정합니다..
	 * 
	 * @param delDate
	 *            DEL_DATE
	 */
	public void setDelDate(Date delDate) {
		this.delDate = delDate;
	}

	/**
	 * DEL_DATE을 가져옵니다..
	 * 
	 * @return DEL_DATE
	 */
	public Date getDelDate() {
		return this.delDate;
	}

	/**
	 * GPS_X을 설정합니다..
	 * 
	 * @param gpsX
	 *            GPS_X
	 */
	public void setGpsX(Integer gpsX) {
		this.gpsX = gpsX;
	}

	/**
	 * GPS_X을 가져옵니다..
	 * 
	 * @return GPS_X
	 */
	public Integer getGpsX() {
		return this.gpsX;
	}

	/**
	 * GPS_Y을 설정합니다..
	 * 
	 * @param gpsY
	 *            GPS_Y
	 */
	public void setGpsY(Integer gpsY) {
		this.gpsY = gpsY;
	}

	/**
	 * GPS_Y을 가져옵니다..
	 * 
	 * @return GPS_Y
	 */
	public Integer getGpsY() {
		return this.gpsY;
	}

	/**
	 * 매물을 올린 부동산 업체 목록을 설정합니다..
	 * 
	 * @param entrySet
	 *            매물을 올린 부동산 업체 목록
	 */
	public void setEntrySet(Set<Entry> entrySet) {
		this.entrySet = entrySet;
	}

	/**
	 * 매물을 올린 부동산 업체를 추가합니다..
	 * 
	 * @param entry
	 *            매물을 올린 부동산 업체
	 */
	public void addEntry(Entry entry) {
		this.entrySet.add(entry);
	}

	/**
	 * 매물을 올린 부동산 업체 목록을 가져옵니다..
	 * 
	 * @return 매물을 올린 부동산 업체 목록
	 */
	public Set<Entry> getEntrySet() {
		return this.entrySet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((agencyId == null) ? 0 : agencyId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Agency other = (Agency) obj;
		if (agencyId == null) {
			if (other.agencyId != null) {
				return false;
			}
		} else if (!agencyId.equals(other.agencyId)) {
			return false;
		}
		return true;
	}

}
