package com.real.fudousan.agency.vo;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.real.fudousan.entry.vo.Entry;
import com.real.fudousan.estate.vo.TransType;
import com.real.fudousan.member.vo.Member;

/**
 * 부동산중개사무소 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Agency implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** AGENCY_ID. */
	private Integer agencyId;

	/** 회원. */
	private Member member;

	/** 중개소이름. */
	private String name;

	/** 사업번호. */
	private int biznum;

	/** 주소 대분류. */
	private String addressMain;

	/** 주소 중분류. */
	private String addressMiddle;

	/** 주소 소분류. */
	private String addressSmall;

	/** 주소 상세. */
	private String addressSub;

	/** 설명. */
	private String text;

	/** 거래 유형. */
	private TransType transType;

	/** CONFIRM. */
	private Integer confirm;

	/** DATE. */
	private Date date;

	/** DEL_DATE. */
	private Date delDate;

	/** GPS_X. */
	private Integer gpsX;

	/** GPS_Y. */
	private Integer gpsY;
}
