package com.real.fudousan.texture.vo;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 텍스쳐 분류 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class TextureType implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** TEXTURE_TYPE_ID. */
	private Integer textureTypeId;

	/** NAME. */
	private String name;

	/** TEXT. */
	private String text;

	/** 텍스쳐 목록. */
	private Set<Texture> textureSet;

	/**
	 * 생성자.
	 */
	public TextureType() {
		this.textureSet = new HashSet<Texture>();
	}

	/**
	 * TEXTURE_TYPE_ID을 설정합니다..
	 * 
	 * @param textureTypeId
	 *            TEXTURE_TYPE_ID
	 */
	public void setTextureTypeId(Integer textureTypeId) {
		this.textureTypeId = textureTypeId;
	}

	/**
	 * TEXTURE_TYPE_ID을 가져옵니다..
	 * 
	 * @return TEXTURE_TYPE_ID
	 */
	public Integer getTextureTypeId() {
		return this.textureTypeId;
	}

	/**
	 * NAME을 설정합니다..
	 * 
	 * @param name
	 *            NAME
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * NAME을 가져옵니다..
	 * 
	 * @return NAME
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * TEXT을 설정합니다..
	 * 
	 * @param text
	 *            TEXT
	 */
	public void setText(String text) {
		this.text = text;
	}

	/**
	 * TEXT을 가져옵니다..
	 * 
	 * @return TEXT
	 */
	public String getText() {
		return this.text;
	}

	/**
	 * 텍스쳐 목록을 설정합니다..
	 * 
	 * @param textureSet
	 *            텍스쳐 목록
	 */
	public void setTextureSet(Set<Texture> textureSet) {
		this.textureSet = textureSet;
	}

	/**
	 * 텍스쳐를 추가합니다..
	 * 
	 * @param texture
	 *            텍스쳐
	 */
	public void addTexture(Texture texture) {
		this.textureSet.add(texture);
	}

	/**
	 * 텍스쳐 목록을 가져옵니다..
	 * 
	 * @return 텍스쳐 목록
	 */
	public Set<Texture> getTextureSet() {
		return this.textureSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((textureTypeId == null) ? 0 : textureTypeId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		TextureType other = (TextureType) obj;
		if (textureTypeId == null) {
			if (other.textureTypeId != null) {
				return false;
			}
		} else if (!textureTypeId.equals(other.textureTypeId)) {
			return false;
		}
		return true;
	}

}
