package com.real.fudousan.advice.vo;

import java.io.Serializable;
import java.util.Date;

import com.real.fudousan.member.vo.Member;
import com.real.fudousan.room.vo.Room;

/**
 * 조언 리스트 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Advice implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 신청한 회원. */
	private int requestMemberId;

	/** 신청받은 회원. */
	private int requestedMemeberId;

	/** 3D 방. */
	private int roomId;

	/** DATE. */
	private Date creDate;

	/** ID. */
	private String id;

	/** REQUEST_DATE. */
	private Date requestDate;
}
