package com.real.fudousan.roomitem.vo;

import java.io.Serializable;

import com.real.fudousan.item.vo.Item;
import com.real.fudousan.room.vo.Room;

/**
 * 방 배치 아이템 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Roomitem implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ROOMITEM_ID. */
	private Integer roomitemId;

	/** 3D 방 아이디. */
	private int roomId;

	/** 3D 방 아이템. */
	private Item item;

	/** X. */
	private Integer x;

	/** Y. */
	private Integer y;

	/** Z. */
	private Integer z;

	/** ROTATE_X. */
	private Integer rotateX;

	/** ROTATE_Y. */
	private Integer rotateY;

	/** ROTATE_Z. */
	private Integer rotateZ;

	/** COLOR. */
	private Integer color;
}
