package com.real.fudousan.reply.vo;

import java.io.Serializable;
import java.util.Date;

import com.real.fudousan.estate.vo.Estate;
import com.real.fudousan.member.vo.Member;

/**
 * 댓글 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Reply implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** REPLY_ID. */
	private Integer replyId;

	/** 매물 아이디. */
	private int estateId;

	/** 회원. */
	private Member member;

	/** TEXT. */
	private String text;

	/** DATE. */
	private Date creDate;
}
