package com.real.fudousan.estate.vo;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.real.fudousan.entry.vo.Entry;
import com.real.fudousan.favorite.vo.Favorite;
import com.real.fudousan.reply.vo.Reply;
import com.real.fudousan.room.vo.Room;

/**
 * 매물 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Estate implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ESTATE_ID. */
	private Integer estateId;

	/** 거래 유형. */
	private TransType transType;

	/** 地区. */
	private String region;

	/** 도시. */
	private Municipalitycode municipalitycode;

	/** 都道府県名. */
	private String prefecture;

	/** 市区町村名. */
	private String municipality;

	/** 地区名. */
	private String districtname;

	/** 最寄駅：名称. */
	private String neareststation;

	/** 最寄駅：距離（分）. */
	private Integer timetoneareststation;

	/** 取引価格（総額）. */
	private Integer tradeprice;

	/** 坪単価. */
	private Integer priceperunit;

	/** 間取り. */
	private String floorplan;

	/** 面積（平方メートル）. */
	private Integer area;

	/** 取引価格（平方メートル単価）. */
	private Integer unitprice;

	/** 土地の形状. */
	private String landshape;

	/** 間口. */
	private Integer frontage;

	/** 延床面積(平方メートル). */
	private Integer totalfloorarea;

	/** 建築年. */
	private String buildingyear;

	/** 建物の構造. */
	private String structure;

	/** 用途. */
	private String use;

	/** 今後の利用目的. */
	private String purpose;

	/** 前面道路：方位. */
	private String direction;

	/** 前面道路：種類. */
	private String classification;

	/** 前面道路：幅員（ｍ）. */
	private Integer breadth;

	/** 都市計画. */
	private String cityplanning;

	/** 建ぺい率（％）. */
	private Integer coverageratio;

	/** 容積率（％）. */
	private Integer floorarearatio;

	/** 取引時点. */
	private String period;

	/** 改装. */
	private String renovation;

	/** 取引の事情等. */
	private String remarks;

	/** DEL_DATE. */
	private Date delDate;

	/** 매물을 올린 부동산 업체 목록. */
	private Set<Entry> entrySet;

	/** 찜하기 목록. */
	private Set<Favorite> favoriteSet;

	/** 댓글 목록. */
	private Set<Reply> replySet;

	/** 3D 방 목록. */
	private Set<Room> roomSet;

	/**
	 * 생성자.
	 */
	public Estate() {
		this.entrySet = new HashSet<Entry>();
		this.favoriteSet = new HashSet<Favorite>();
		this.replySet = new HashSet<Reply>();
		this.roomSet = new HashSet<Room>();
	}

	/**
	 * ESTATE_ID을 설정합니다..
	 * 
	 * @param estateId
	 *            ESTATE_ID
	 */
	public void setEstateId(Integer estateId) {
		this.estateId = estateId;
	}

	/**
	 * ESTATE_ID을 가져옵니다..
	 * 
	 * @return ESTATE_ID
	 */
	public Integer getEstateId() {
		return this.estateId;
	}

	/**
	 * 거래 유형을 설정합니다..
	 * 
	 * @param transType
	 *            거래 유형
	 */
	public void setTransType(TransType transType) {
		this.transType = transType;
	}

	/**
	 * 거래 유형을 가져옵니다..
	 * 
	 * @return 거래 유형
	 */
	public TransType getTransType() {
		return this.transType;
	}

	/**
	 * 地区을 설정합니다..
	 * 
	 * @param region
	 *            地区
	 */
	public void setRegion(String region) {
		this.region = region;
	}

	/**
	 * 地区을 가져옵니다..
	 * 
	 * @return 地区
	 */
	public String getRegion() {
		return this.region;
	}

	/**
	 * 도시을 설정합니다..
	 * 
	 * @param municipalitycode
	 *            도시
	 */
	public void setMunicipalitycode(Municipalitycode municipalitycode) {
		this.municipalitycode = municipalitycode;
	}

	/**
	 * 도시을 가져옵니다..
	 * 
	 * @return 도시
	 */
	public Municipalitycode getMunicipalitycode() {
		return this.municipalitycode;
	}

	/**
	 * 都道府県名을 설정합니다..
	 * 
	 * @param prefecture
	 *            都道府県名
	 */
	public void setPrefecture(String prefecture) {
		this.prefecture = prefecture;
	}

	/**
	 * 都道府県名을 가져옵니다..
	 * 
	 * @return 都道府県名
	 */
	public String getPrefecture() {
		return this.prefecture;
	}

	/**
	 * 市区町村名을 설정합니다..
	 * 
	 * @param municipality
	 *            市区町村名
	 */
	public void setMunicipality(String municipality) {
		this.municipality = municipality;
	}

	/**
	 * 市区町村名을 가져옵니다..
	 * 
	 * @return 市区町村名
	 */
	public String getMunicipality() {
		return this.municipality;
	}

	/**
	 * 地区名을 설정합니다..
	 * 
	 * @param districtname
	 *            地区名
	 */
	public void setDistrictname(String districtname) {
		this.districtname = districtname;
	}

	/**
	 * 地区名을 가져옵니다..
	 * 
	 * @return 地区名
	 */
	public String getDistrictname() {
		return this.districtname;
	}

	/**
	 * 最寄駅：名称을 설정합니다..
	 * 
	 * @param neareststation
	 *            最寄駅：名称
	 */
	public void setNeareststation(String neareststation) {
		this.neareststation = neareststation;
	}

	/**
	 * 最寄駅：名称을 가져옵니다..
	 * 
	 * @return 最寄駅：名称
	 */
	public String getNeareststation() {
		return this.neareststation;
	}

	/**
	 * 最寄駅：距離（分）을 설정합니다..
	 * 
	 * @param timetoneareststation
	 *            最寄駅：距離（分）
	 */
	public void setTimetoneareststation(Integer timetoneareststation) {
		this.timetoneareststation = timetoneareststation;
	}

	/**
	 * 最寄駅：距離（分）을 가져옵니다..
	 * 
	 * @return 最寄駅：距離（分）
	 */
	public Integer getTimetoneareststation() {
		return this.timetoneareststation;
	}

	/**
	 * 取引価格（総額）을 설정합니다..
	 * 
	 * @param tradeprice
	 *            取引価格（総額）
	 */
	public void setTradeprice(Integer tradeprice) {
		this.tradeprice = tradeprice;
	}

	/**
	 * 取引価格（総額）을 가져옵니다..
	 * 
	 * @return 取引価格（総額）
	 */
	public Integer getTradeprice() {
		return this.tradeprice;
	}

	/**
	 * 坪単価을 설정합니다..
	 * 
	 * @param priceperunit
	 *            坪単価
	 */
	public void setPriceperunit(Integer priceperunit) {
		this.priceperunit = priceperunit;
	}

	/**
	 * 坪単価을 가져옵니다..
	 * 
	 * @return 坪単価
	 */
	public Integer getPriceperunit() {
		return this.priceperunit;
	}

	/**
	 * 間取り을 설정합니다..
	 * 
	 * @param floorplan
	 *            間取り
	 */
	public void setFloorplan(String floorplan) {
		this.floorplan = floorplan;
	}

	/**
	 * 間取り을 가져옵니다..
	 * 
	 * @return 間取り
	 */
	public String getFloorplan() {
		return this.floorplan;
	}

	/**
	 * 面積（平方メートル）을 설정합니다..
	 * 
	 * @param area
	 *            面積（平方メートル）
	 */
	public void setArea(Integer area) {
		this.area = area;
	}

	/**
	 * 面積（平方メートル）을 가져옵니다..
	 * 
	 * @return 面積（平方メートル）
	 */
	public Integer getArea() {
		return this.area;
	}

	/**
	 * 取引価格（平方メートル単価）을 설정합니다..
	 * 
	 * @param unitprice
	 *            取引価格（平方メートル単価）
	 */
	public void setUnitprice(Integer unitprice) {
		this.unitprice = unitprice;
	}

	/**
	 * 取引価格（平方メートル単価）을 가져옵니다..
	 * 
	 * @return 取引価格（平方メートル単価）
	 */
	public Integer getUnitprice() {
		return this.unitprice;
	}

	/**
	 * 土地の形状을 설정합니다..
	 * 
	 * @param landshape
	 *            土地の形状
	 */
	public void setLandshape(String landshape) {
		this.landshape = landshape;
	}

	/**
	 * 土地の形状을 가져옵니다..
	 * 
	 * @return 土地の形状
	 */
	public String getLandshape() {
		return this.landshape;
	}

	/**
	 * 間口을 설정합니다..
	 * 
	 * @param frontage
	 *            間口
	 */
	public void setFrontage(Integer frontage) {
		this.frontage = frontage;
	}

	/**
	 * 間口을 가져옵니다..
	 * 
	 * @return 間口
	 */
	public Integer getFrontage() {
		return this.frontage;
	}

	/**
	 * 延床面積(平方メートル)을 설정합니다..
	 * 
	 * @param totalfloorarea
	 *            延床面積(平方メートル)
	 */
	public void setTotalfloorarea(Integer totalfloorarea) {
		this.totalfloorarea = totalfloorarea;
	}

	/**
	 * 延床面積(平方メートル)을 가져옵니다..
	 * 
	 * @return 延床面積(平方メートル)
	 */
	public Integer getTotalfloorarea() {
		return this.totalfloorarea;
	}

	/**
	 * 建築年을 설정합니다..
	 * 
	 * @param buildingyear
	 *            建築年
	 */
	public void setBuildingyear(String buildingyear) {
		this.buildingyear = buildingyear;
	}

	/**
	 * 建築年을 가져옵니다..
	 * 
	 * @return 建築年
	 */
	public String getBuildingyear() {
		return this.buildingyear;
	}

	/**
	 * 建物の構造을 설정합니다..
	 * 
	 * @param structure
	 *            建物の構造
	 */
	public void setStructure(String structure) {
		this.structure = structure;
	}

	/**
	 * 建物の構造을 가져옵니다..
	 * 
	 * @return 建物の構造
	 */
	public String getStructure() {
		return this.structure;
	}

	/**
	 * 用途을 설정합니다..
	 * 
	 * @param use
	 *            用途
	 */
	public void setUse(String use) {
		this.use = use;
	}

	/**
	 * 用途을 가져옵니다..
	 * 
	 * @return 用途
	 */
	public String getUse() {
		return this.use;
	}

	/**
	 * 今後の利用目的을 설정합니다..
	 * 
	 * @param purpose
	 *            今後の利用目的
	 */
	public void setPurpose(String purpose) {
		this.purpose = purpose;
	}

	/**
	 * 今後の利用目的을 가져옵니다..
	 * 
	 * @return 今後の利用目的
	 */
	public String getPurpose() {
		return this.purpose;
	}

	/**
	 * 前面道路：方位을 설정합니다..
	 * 
	 * @param direction
	 *            前面道路：方位
	 */
	public void setDirection(String direction) {
		this.direction = direction;
	}

	/**
	 * 前面道路：方位을 가져옵니다..
	 * 
	 * @return 前面道路：方位
	 */
	public String getDirection() {
		return this.direction;
	}

	/**
	 * 前面道路：種類을 설정합니다..
	 * 
	 * @param classification
	 *            前面道路：種類
	 */
	public void setClassification(String classification) {
		this.classification = classification;
	}

	/**
	 * 前面道路：種類을 가져옵니다..
	 * 
	 * @return 前面道路：種類
	 */
	public String getClassification() {
		return this.classification;
	}

	/**
	 * 前面道路：幅員（ｍ）을 설정합니다..
	 * 
	 * @param breadth
	 *            前面道路：幅員（ｍ）
	 */
	public void setBreadth(Integer breadth) {
		this.breadth = breadth;
	}

	/**
	 * 前面道路：幅員（ｍ）을 가져옵니다..
	 * 
	 * @return 前面道路：幅員（ｍ）
	 */
	public Integer getBreadth() {
		return this.breadth;
	}

	/**
	 * 都市計画을 설정합니다..
	 * 
	 * @param cityplanning
	 *            都市計画
	 */
	public void setCityplanning(String cityplanning) {
		this.cityplanning = cityplanning;
	}

	/**
	 * 都市計画을 가져옵니다..
	 * 
	 * @return 都市計画
	 */
	public String getCityplanning() {
		return this.cityplanning;
	}

	/**
	 * 建ぺい率（％）을 설정합니다..
	 * 
	 * @param coverageratio
	 *            建ぺい率（％）
	 */
	public void setCoverageratio(Integer coverageratio) {
		this.coverageratio = coverageratio;
	}

	/**
	 * 建ぺい率（％）을 가져옵니다..
	 * 
	 * @return 建ぺい率（％）
	 */
	public Integer getCoverageratio() {
		return this.coverageratio;
	}

	/**
	 * 容積率（％）을 설정합니다..
	 * 
	 * @param floorarearatio
	 *            容積率（％）
	 */
	public void setFloorarearatio(Integer floorarearatio) {
		this.floorarearatio = floorarearatio;
	}

	/**
	 * 容積率（％）을 가져옵니다..
	 * 
	 * @return 容積率（％）
	 */
	public Integer getFloorarearatio() {
		return this.floorarearatio;
	}

	/**
	 * 取引時点을 설정합니다..
	 * 
	 * @param period
	 *            取引時点
	 */
	public void setPeriod(String period) {
		this.period = period;
	}

	/**
	 * 取引時点을 가져옵니다..
	 * 
	 * @return 取引時点
	 */
	public String getPeriod() {
		return this.period;
	}

	/**
	 * 改装을 설정합니다..
	 * 
	 * @param renovation
	 *            改装
	 */
	public void setRenovation(String renovation) {
		this.renovation = renovation;
	}

	/**
	 * 改装을 가져옵니다..
	 * 
	 * @return 改装
	 */
	public String getRenovation() {
		return this.renovation;
	}

	/**
	 * 取引の事情等을 설정합니다..
	 * 
	 * @param remarks
	 *            取引の事情等
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	/**
	 * 取引の事情等을 가져옵니다..
	 * 
	 * @return 取引の事情等
	 */
	public String getRemarks() {
		return this.remarks;
	}

	/**
	 * DEL_DATE을 설정합니다..
	 * 
	 * @param delDate
	 *            DEL_DATE
	 */
	public void setDelDate(Date delDate) {
		this.delDate = delDate;
	}

	/**
	 * DEL_DATE을 가져옵니다..
	 * 
	 * @return DEL_DATE
	 */
	public Date getDelDate() {
		return this.delDate;
	}

	/**
	 * 매물을 올린 부동산 업체 목록을 설정합니다..
	 * 
	 * @param entrySet
	 *            매물을 올린 부동산 업체 목록
	 */
	public void setEntrySet(Set<Entry> entrySet) {
		this.entrySet = entrySet;
	}

	/**
	 * 매물을 올린 부동산 업체를 추가합니다..
	 * 
	 * @param entry
	 *            매물을 올린 부동산 업체
	 */
	public void addEntry(Entry entry) {
		this.entrySet.add(entry);
	}

	/**
	 * 매물을 올린 부동산 업체 목록을 가져옵니다..
	 * 
	 * @return 매물을 올린 부동산 업체 목록
	 */
	public Set<Entry> getEntrySet() {
		return this.entrySet;
	}

	/**
	 * 찜하기 목록을 설정합니다..
	 * 
	 * @param favoriteSet
	 *            찜하기 목록
	 */
	public void setFavoriteSet(Set<Favorite> favoriteSet) {
		this.favoriteSet = favoriteSet;
	}

	/**
	 * 찜하기를 추가합니다..
	 * 
	 * @param favorite
	 *            찜하기
	 */
	public void addFavorite(Favorite favorite) {
		this.favoriteSet.add(favorite);
	}

	/**
	 * 찜하기 목록을 가져옵니다..
	 * 
	 * @return 찜하기 목록
	 */
	public Set<Favorite> getFavoriteSet() {
		return this.favoriteSet;
	}

	/**
	 * 댓글 목록을 설정합니다..
	 * 
	 * @param replySet
	 *            댓글 목록
	 */
	public void setReplySet(Set<Reply> replySet) {
		this.replySet = replySet;
	}

	/**
	 * 댓글를 추가합니다..
	 * 
	 * @param reply
	 *            댓글
	 */
	public void addReply(Reply reply) {
		this.replySet.add(reply);
	}

	/**
	 * 댓글 목록을 가져옵니다..
	 * 
	 * @return 댓글 목록
	 */
	public Set<Reply> getReplySet() {
		return this.replySet;
	}

	/**
	 * 3D 방 목록을 설정합니다..
	 * 
	 * @param roomSet
	 *            3D 방 목록
	 */
	public void setRoomSet(Set<Room> roomSet) {
		this.roomSet = roomSet;
	}

	/**
	 * 3D 방를 추가합니다..
	 * 
	 * @param room
	 *            3D 방
	 */
	public void addRoom(Room room) {
		this.roomSet.add(room);
	}

	/**
	 * 3D 방 목록을 가져옵니다..
	 * 
	 * @return 3D 방 목록
	 */
	public Set<Room> getRoomSet() {
		return this.roomSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((estateId == null) ? 0 : estateId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Estate other = (Estate) obj;
		if (estateId == null) {
			if (other.estateId != null) {
				return false;
			}
		} else if (!estateId.equals(other.estateId)) {
			return false;
		}
		return true;
	}

}
