package com.real.fudousan.estate.vo;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.real.fudousan.entry.vo.Entry;
import com.real.fudousan.favorite.vo.Favorite;
import com.real.fudousan.reply.vo.Reply;
import com.real.fudousan.room.vo.Room;

/**
 * 매물 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Estate implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ESTATE_ID. */
	private Integer estateId;

	/** 거래 유형. */
	private TransType transType;

	/** 地区. */
	private String region;

	/** 도시. */
	private MunicipalityCode municipalitycode;

	/** 都道府県名. */
	private String prefecture;

	/** 市区町村名. */
	private String municipality;

	/** 地区名. */
	private String districtname;

	/** 最寄駅：名称. */
	private String neareststation;

	/** 最寄駅：距離（分）. */
	private Integer timetoneareststation;

	/** 取引価格（総額）. */
	private Integer tradeprice;

	/** 坪単価. */
	private Integer priceperunit;

	/** 間取り. */
	private String floorplan;

	/** 面積（平方メートル）. */
	private Integer area;

	/** 取引価格（平方メートル単価）. */
	private Integer unitprice;

	/** 土地の形状. */
	private String landshape;

	/** 間口. */
	private Integer frontage;

	/** 延床面積(平方メートル). */
	private Integer totalfloorarea;

	/** 建築年. */
	private String buildingyear;

	/** 建物の構造. */
	private String structure;

	/** 用途. */
	private String use;

	/** 今後の利用目的. */
	private String purpose;

	/** 前面道路：方位. */
	private String direction;

	/** 前面道路：種類. */
	private String classification;

	/** 前面道路：幅員（ｍ）. */
	private Integer breadth;

	/** 都市計画. */
	private String cityplanning;

	/** 建ぺい率（％）. */
	private Integer coverageratio;

	/** 容積率（％）. */
	private Integer floorarearatio;

	/** 取引時点. */
	private String period;

	/** 改装. */
	private String renovation;

	/** 取引の事情等. */
	private String remarks;

	/** DEL_DATE. */
	private Date delDate;
}
