package com.real.fudousan.estate.vo;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 도시 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Municipalitycode implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** MunicipalityCode_ID. */
	private Integer municipalitycodeId;

	/** NAME. */
	private String name;

	/** 매물 목록. */
	private Set<Estate> estateSet;

	/**
	 * 생성자.
	 */
	public Municipalitycode() {
		this.estateSet = new HashSet<Estate>();
	}

	/**
	 * MunicipalityCode_ID을 설정합니다..
	 * 
	 * @param municipalitycodeId
	 *            MunicipalityCode_ID
	 */
	public void setMunicipalitycodeId(Integer municipalitycodeId) {
		this.municipalitycodeId = municipalitycodeId;
	}

	/**
	 * MunicipalityCode_ID을 가져옵니다..
	 * 
	 * @return MunicipalityCode_ID
	 */
	public Integer getMunicipalitycodeId() {
		return this.municipalitycodeId;
	}

	/**
	 * NAME을 설정합니다..
	 * 
	 * @param name
	 *            NAME
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * NAME을 가져옵니다..
	 * 
	 * @return NAME
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * 매물 목록을 설정합니다..
	 * 
	 * @param estateSet
	 *            매물 목록
	 */
	public void setEstateSet(Set<Estate> estateSet) {
		this.estateSet = estateSet;
	}

	/**
	 * 매물를 추가합니다..
	 * 
	 * @param estate
	 *            매물
	 */
	public void addEstate(Estate estate) {
		this.estateSet.add(estate);
	}

	/**
	 * 매물 목록을 가져옵니다..
	 * 
	 * @return 매물 목록
	 */
	public Set<Estate> getEstateSet() {
		return this.estateSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((municipalitycodeId == null) ? 0 : municipalitycodeId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Municipalitycode other = (Municipalitycode) obj;
		if (municipalitycodeId == null) {
			if (other.municipalitycodeId != null) {
				return false;
			}
		} else if (!municipalitycodeId.equals(other.municipalitycodeId)) {
			return false;
		}
		return true;
	}

}
