package com.real.fudousan.estate.vo;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 도시 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Municipalitycode implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** MunicipalityCode_ID. */
	private Integer municipalitycodeId;

	/** NAME. */
	private String name;
}
