package com.real.fudousan.estate.vo;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 거래 유형 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class TransType implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 거래 유형 ID. */
	private Integer transTypeId;

	/** 거래 유형 이름. */
	private String name;

	/** 부동산중개사무소 목록. */
	private Set<Agency> agencySet;

	/** 매물 목록. */
	private Set<Estate> estateSet;

	/**
	 * 생성자.
	 */
	public TransType() {
		this.agencySet = new HashSet<Agency>();
		this.estateSet = new HashSet<Estate>();
	}

	/**
	 * 거래 유형 ID을 설정합니다..
	 * 
	 * @param transTypeId
	 *            거래 유형 ID
	 */
	public void setTransTypeId(Integer transTypeId) {
		this.transTypeId = transTypeId;
	}

	/**
	 * 거래 유형 ID을 가져옵니다..
	 * 
	 * @return 거래 유형 ID
	 */
	public Integer getTransTypeId() {
		return this.transTypeId;
	}

	/**
	 * 거래 유형 이름을 설정합니다..
	 * 
	 * @param name
	 *            거래 유형 이름
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * 거래 유형 이름을 가져옵니다..
	 * 
	 * @return 거래 유형 이름
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * 부동산중개사무소 목록을 설정합니다..
	 * 
	 * @param agencySet
	 *            부동산중개사무소 목록
	 */
	public void setAgencySet(Set<Agency> agencySet) {
		this.agencySet = agencySet;
	}

	/**
	 * 부동산중개사무소를 추가합니다..
	 * 
	 * @param agency
	 *            부동산중개사무소
	 */
	public void addAgency(Agency agency) {
		this.agencySet.add(agency);
	}

	/**
	 * 부동산중개사무소 목록을 가져옵니다..
	 * 
	 * @return 부동산중개사무소 목록
	 */
	public Set<Agency> getAgencySet() {
		return this.agencySet;
	}

	/**
	 * 매물 목록을 설정합니다..
	 * 
	 * @param estateSet
	 *            매물 목록
	 */
	public void setEstateSet(Set<Estate> estateSet) {
		this.estateSet = estateSet;
	}

	/**
	 * 매물를 추가합니다..
	 * 
	 * @param estate
	 *            매물
	 */
	public void addEstate(Estate estate) {
		this.estateSet.add(estate);
	}

	/**
	 * 매물 목록을 가져옵니다..
	 * 
	 * @return 매물 목록
	 */
	public Set<Estate> getEstateSet() {
		return this.estateSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((transTypeId == null) ? 0 : transTypeId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		TransType other = (TransType) obj;
		if (transTypeId == null) {
			if (other.transTypeId != null) {
				return false;
			}
		} else if (!transTypeId.equals(other.transTypeId)) {
			return false;
		}
		return true;
	}

}
