package com.real.fudousan.estate.vo;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import com.real.fudousan.agency.vo.Agency;

/**
 * 거래 유형 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class TransType implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 거래 유형 ID. */
	private Integer transTypeId;

	/** 거래 유형 이름. */
	private String transName;
}
