package com.real.fudousan.roomwall.vo;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 방 벽 연결 지점 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class RoomWallConnector implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** CONNECTOR_ID. */
	private Integer connectorId;

	/** X. */
	private Integer x;

	/** Y. */
	private Integer y;

	/** 방 벽 목록. */
	private Set<RoomWall> roomWallSet;

	/** 방 벽 목록. */
	private Set<RoomWall> roomWallSet;

	/**
	 * 생성자.
	 */
	public RoomWallConnector() {
		this.roomWallSet = new HashSet<RoomWall>();
	}

	/**
	 * CONNECTOR_ID을 설정합니다..
	 * 
	 * @param connectorId
	 *            CONNECTOR_ID
	 */
	public void setConnectorId(Integer connectorId) {
		this.connectorId = connectorId;
	}

	/**
	 * CONNECTOR_ID을 가져옵니다..
	 * 
	 * @return CONNECTOR_ID
	 */
	public Integer getConnectorId() {
		return this.connectorId;
	}

	/**
	 * X을 설정합니다..
	 * 
	 * @param x
	 *            X
	 */
	public void setX(Integer x) {
		this.x = x;
	}

	/**
	 * X을 가져옵니다..
	 * 
	 * @return X
	 */
	public Integer getX() {
		return this.x;
	}

	/**
	 * Y을 설정합니다..
	 * 
	 * @param y
	 *            Y
	 */
	public void setY(Integer y) {
		this.y = y;
	}

	/**
	 * Y을 가져옵니다..
	 * 
	 * @return Y
	 */
	public Integer getY() {
		return this.y;
	}

	/**
	 * 방 벽 목록을 설정합니다..
	 * 
	 * @param roomWallSet
	 *            방 벽 목록
	 */
	public void setRoomWallSet(Set<RoomWall> roomWallSet) {
		this.roomWallSet = roomWallSet;
	}

	/**
	 * 방 벽를 추가합니다..
	 * 
	 * @param roomWall
	 *            방 벽
	 */
	public void addRoomWall(RoomWall roomWall) {
		this.roomWallSet.add(roomWall);
	}

	/**
	 * 방 벽 목록을 가져옵니다..
	 * 
	 * @return 방 벽 목록
	 */
	public Set<RoomWall> getRoomWallSet() {
		return this.roomWallSet;
	}

	/**
	 * 방 벽 목록을 설정합니다..
	 * 
	 * @param roomWallSet
	 *            방 벽 목록
	 */
	public void setRoomWallSet(Set<RoomWall> roomWallSet) {
		this.roomWallSet = roomWallSet;
	}

	/**
	 * 방 벽를 추가합니다..
	 * 
	 * @param roomWall
	 *            방 벽
	 */
	public void addRoomWall(RoomWall roomWall) {
		this.roomWallSet.add(roomWall);
	}

	/**
	 * 방 벽 목록을 가져옵니다..
	 * 
	 * @return 방 벽 목록
	 */
	public Set<RoomWall> getRoomWallSet() {
		return this.roomWallSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((connectorId == null) ? 0 : connectorId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		RoomWallConnector other = (RoomWallConnector) obj;
		if (connectorId == null) {
			if (other.connectorId != null) {
				return false;
			}
		} else if (!connectorId.equals(other.connectorId)) {
			return false;
		}
		return true;
	}

}
