package com.real.fudousan.roomwall.vo;

import java.io.Serializable;

import com.real.fudousan.room.vo.Room;
import com.real.fudousan.texture.vo.Texture;

/**
 * 방 벽 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class RoomWall implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 3D 방. */
	private Room room;

	/** 방 벽 연결 지점. */
	private RoomWallConnector roomWallConnector1;

	/** 방 벽 연결 지점. */
	private RoomWallConnector roomWallConnector2;

	/** TYPE. */
	private String type;

	/** 텍스쳐. */
	private Texture frontTexture;

	/** 텍스쳐. */
	private Texture backTexture;
}
