package com.real.fudousan.roomwall.vo;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 방 벽 연결 지점 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class RoomWallConnector implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** CONNECTOR_ID. */
	private Integer connectorId;

	/** X. */
	private Double x;

	/** Y. */
	private Double y;

	public RoomWallConnector() {
		super();
	}

	public RoomWallConnector(Integer connectorId, Double x, Double y) {
		super();
		this.connectorId = connectorId;
		this.x = x;
		this.y = y;
	}

	public Integer getConnectorId() {
		return connectorId;
	}

	public void setConnectorId(Integer connectorId) {
		this.connectorId = connectorId;
	}

	public Double getX() {
		return x;
	}

	public void setX(Double x) {
		this.x = x;
	}

	public Double getY() {
		return y;
	}

	public void setY(Double y) {
		this.y = y;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Override
	public String toString() {
		return "RoomWallConnector [connectorId=" + connectorId + ", x=" + x + ", y=" + y + "]";
	}
}
