package com.real.fudousan.roomwall.vo;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 방 벽 연결 지점 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class RoomWallConnector implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** CONNECTOR_ID. */
	private Integer connectorId;

	/** X. */
	private Integer x;

	/** Y. */
	private Integer y;
}
