package com.real.fudousan.favorite.vo;

import java.io.Serializable;
import java.util.Date;

import com.real.fudousan.estate.vo.Estate;
import com.real.fudousan.member.vo.Member;

/**
 * 찜하기 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Favorite implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 회원 ID. */
	private int memberId;

	/** 매물. */
	private Estate estate;

	/** DATE. */
	private Date date;
}
