package com.real.fudousan.member.vo;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.real.fudousan.advice.vo.Advice;
import com.real.fudousan.agency.vo.Agency;
import com.real.fudousan.favorite.vo.Favorite;
import com.real.fudousan.memberfile.vo.MemberFile;
import com.real.fudousan.reply.vo.Reply;
import com.real.fudousan.room.vo.Room;
import com.real.fudousan.texture.vo.Texture;

/**
 * 회원 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Member implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** MEMBER_ID. */
	private Integer memberId;

	/** EMAIL. */
	private String email;

	/** PASSWORD. */
	private String password;

	/** 전화번호. */
	private String phone;

	/** 사진. */
	private String picture;

	/** 소개. */
	private String text;

	/** 가입 날. */
	private Date date;

	/** 탈퇴 날. */
	private Date delDate;

	/** 권한. */
	private Permission permission;

	/** 디자이너 유무. */
	private Integer designer;
}
