package com.real.fudousan.member.vo;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 권한 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Permission implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** PERMISSION_ID. */
	private Integer permissionId;

	/** NAME. */
	private String name;
}
