package com.real.fudousan.room.vo;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.real.fudousan.estate.vo.Estate;
import com.real.fudousan.member.vo.Member;
import com.real.fudousan.texture.vo.Texture;

/**
 * 3D 방 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Room implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ROOM_ID. */
	private Integer roomId;

	/** 매물 아이디. */
	private int estateId;

	/** 스냅샷. */
	private String snapshot;

	/** 벽 도면. */
	private String map;

	/** DATE. */
	private Date date;

	/** DEL_DATE. */
	private Date delDate;

	/** HEIGTH. */
	private Integer heigth;

	/** 텍스쳐. */
	private Texture floorTexture;

	/** 텍스쳐. */
	private Texture ceilingTexture;

	/** 회원 아이디. */
	private int memberId;
}
