package com.real.fudousan.item.vo;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 3D 방 내부 아이템 들 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Item implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ITEM_ID. */
	private Integer itemId;

	/** 아이템 분류. */
	private ItemType itemType;

	/** NAME. */
	private String name;

	/** TEXT. */
	private String text;

	/** FILE. */
	private String file;

	/** 아이템 참고 사이트 목록. */
	private Set<RefSite> refSiteSet;

	/** 방 배치 아이템 목록. */
	private Set<Roomitem> roomitemSet;

	/**
	 * 생성자.
	 */
	public Item() {
		this.refSiteSet = new HashSet<RefSite>();
		this.roomitemSet = new HashSet<Roomitem>();
	}

	/**
	 * ITEM_ID을 설정합니다..
	 * 
	 * @param itemId
	 *            ITEM_ID
	 */
	public void setItemId(Integer itemId) {
		this.itemId = itemId;
	}

	/**
	 * ITEM_ID을 가져옵니다..
	 * 
	 * @return ITEM_ID
	 */
	public Integer getItemId() {
		return this.itemId;
	}

	/**
	 * 아이템 분류을 설정합니다..
	 * 
	 * @param itemType
	 *            아이템 분류
	 */
	public void setItemType(ItemType itemType) {
		this.itemType = itemType;
	}

	/**
	 * 아이템 분류을 가져옵니다..
	 * 
	 * @return 아이템 분류
	 */
	public ItemType getItemType() {
		return this.itemType;
	}

	/**
	 * NAME을 설정합니다..
	 * 
	 * @param name
	 *            NAME
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * NAME을 가져옵니다..
	 * 
	 * @return NAME
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * TEXT을 설정합니다..
	 * 
	 * @param text
	 *            TEXT
	 */
	public void setText(String text) {
		this.text = text;
	}

	/**
	 * TEXT을 가져옵니다..
	 * 
	 * @return TEXT
	 */
	public String getText() {
		return this.text;
	}

	/**
	 * FILE을 설정합니다..
	 * 
	 * @param file
	 *            FILE
	 */
	public void setFile(String file) {
		this.file = file;
	}

	/**
	 * FILE을 가져옵니다..
	 * 
	 * @return FILE
	 */
	public String getFile() {
		return this.file;
	}

	/**
	 * 아이템 참고 사이트 목록을 설정합니다..
	 * 
	 * @param refSiteSet
	 *            아이템 참고 사이트 목록
	 */
	public void setRefSiteSet(Set<RefSite> refSiteSet) {
		this.refSiteSet = refSiteSet;
	}

	/**
	 * 아이템 참고 사이트를 추가합니다..
	 * 
	 * @param refSite
	 *            아이템 참고 사이트
	 */
	public void addRefSite(RefSite refSite) {
		this.refSiteSet.add(refSite);
	}

	/**
	 * 아이템 참고 사이트 목록을 가져옵니다..
	 * 
	 * @return 아이템 참고 사이트 목록
	 */
	public Set<RefSite> getRefSiteSet() {
		return this.refSiteSet;
	}

	/**
	 * 방 배치 아이템 목록을 설정합니다..
	 * 
	 * @param roomitemSet
	 *            방 배치 아이템 목록
	 */
	public void setRoomitemSet(Set<Roomitem> roomitemSet) {
		this.roomitemSet = roomitemSet;
	}

	/**
	 * 방 배치 아이템를 추가합니다..
	 * 
	 * @param roomitem
	 *            방 배치 아이템
	 */
	public void addRoomitem(Roomitem roomitem) {
		this.roomitemSet.add(roomitem);
	}

	/**
	 * 방 배치 아이템 목록을 가져옵니다..
	 * 
	 * @return 방 배치 아이템 목록
	 */
	public Set<Roomitem> getRoomitemSet() {
		return this.roomitemSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((itemId == null) ? 0 : itemId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Item other = (Item) obj;
		if (itemId == null) {
			if (other.itemId != null) {
				return false;
			}
		} else if (!itemId.equals(other.itemId)) {
			return false;
		}
		return true;
	}

}
