package com.real.fudousan.item.vo;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 아이템 분류 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ItemType implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ITEM_TYPE_ID. */
	private Integer itemTypeId;

	/** NAME. */
	private String name;
}
