package com.real.fudousan.item.vo;

import java.io.Serializable;
import java.util.Date;

/**
 * 아이템 참고 사이트 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class RefSite implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID. */
	private Integer id;

	/** URL. */
	private String url;

	/** DATE. */
	private Date creDate;

	/** TEXT. */
	private String text;
}
