package com.real.fudousan.item.vo;

import java.io.Serializable;
import java.util.Date;

/**
 * 아이템 참고 사이트 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class RefSite implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID. */
	private Integer id;

	/** URL. */
	private String url;

	/** DATE. */
	private Date date;

	/** TEXT. */
	private String text;

	/** 3D 방 내부 아이템 들. */
	private Item item;

	/**
	 * 생성자.
	 */
	public RefSite() {
	}

	/**
	 * ID을 설정합니다..
	 * 
	 * @param id
	 *            ID
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * ID을 가져옵니다..
	 * 
	 * @return ID
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * URL을 설정합니다..
	 * 
	 * @param url
	 *            URL
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * URL을 가져옵니다..
	 * 
	 * @return URL
	 */
	public String getUrl() {
		return this.url;
	}

	/**
	 * DATE을 설정합니다..
	 * 
	 * @param date
	 *            DATE
	 */
	public void setDate(Date date) {
		this.date = date;
	}

	/**
	 * DATE을 가져옵니다..
	 * 
	 * @return DATE
	 */
	public Date getDate() {
		return this.date;
	}

	/**
	 * TEXT을 설정합니다..
	 * 
	 * @param text
	 *            TEXT
	 */
	public void setText(String text) {
		this.text = text;
	}

	/**
	 * TEXT을 가져옵니다..
	 * 
	 * @return TEXT
	 */
	public String getText() {
		return this.text;
	}

	/**
	 * 3D 방 내부 아이템 들을 설정합니다..
	 * 
	 * @param item
	 *            3D 방 내부 아이템 들
	 */
	public void setItem(Item item) {
		this.item = item;
	}

	/**
	 * 3D 방 내부 아이템 들을 가져옵니다..
	 * 
	 * @return 3D 방 내부 아이템 들
	 */
	public Item getItem() {
		return this.item;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		RefSite other = (RefSite) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
