package com.real.fudousan.item.vo;

import java.io.Serializable;
import java.util.Date;

/**
 * 아이템 참고 사이트 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class RefSite implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID. */
	private Integer id;

	/** URL. */
	private String url;

	/** DATE. */
	private Date creDate;

	/** TEXT. */
	private String text;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Date getCreDate() {
		return creDate;
	}

	public void setCreDate(Date creDate) {
		this.creDate = creDate;
	}

	public String getText() {
		return text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public RefSite() {
		super();
	}

	public RefSite(Integer id, String url, Date creDate, String text) {
		super();
		this.id = id;
		this.url = url;
		this.creDate = creDate;
		this.text = text;
	}

	@Override
	public String toString() {
		return "RefSite [id=" + id + ", url=" + url + ", creDate=" + creDate + ", text=" + text + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		RefSite other = (RefSite) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}
}
